name: 'jaffle_shop_init'
version: '1.0.0'
config-version: 2

profile: pg

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop_init:
    +persist_docs:
      relation: true
      columns: true

    raw:
      +schema: seeds
      +tags: learn

    extended:
      +schema: seeds_ext
      +tags: extended

models:
  jaffle_shop_init:
    +persist_docs:
      relation: true
      columns: true

    prep:
      +materialized: table
      +schema: src
      +tags: learn

on-run-end:
  - "{% do grant_select(role='lecteur') %}"

flags:
  require_unique_project_resource_names: true

