name: 'jaffle_shop_init'
version: '1.0.0'
config-version: 2

profile: duckdb

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop_init:
    +persist_docs:
      relation: true
      columns: true

    simple:
      +schema: seeds
      +tags: simple

    extended:
      +schema: seeds_ext
      +tags: extended

models:
  jaffle_shop_init:
    +persist_docs:
      relation: true
      columns: true

    prep:
      +materialized: table
      +schema: src
      simple:
        +tags: simple
      extended:
        +tags: extended

on-run-end:
  - "{% do grant_select(role='lecteur') %}"

flags:
  require_unique_project_resource_names: true
# 2 seeds can't have the same filename
# a seed and a model can't have the same name
# use alias to rename the table if seed filename is not what you expect
